# Generated by Django 3.1.5 on 2021-02-26 03:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Full Name :')),
                ('email', models.EmailField(max_length=200, verbose_name='Email :')),
                ('purpose', models.CharField(choices=[('Purpose1', 'Purpose1'), ('Purpose2', 'Purpose2')], max_length=200, verbose_name='Purpose :')),
                ('msg', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Full Name :')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10, verbose_name='Gender :')),
                ('city', models.CharField(choices=[('', 'Select'), ('Baroda', 'Baroda'), ('Surat', 'Surat'), ('Ahmedabad', 'Ahmedabad')], default='Baroda', max_length=100, verbose_name='City')),
                ('contactno', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('zipcode', models.IntegerField(null=True, verbose_name='Zip Code :')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Enter Name :')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Enter Email :')),
                ('password', models.CharField(max_length=500, null=True, verbose_name='Enter Password')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(null=True)),
                ('userperson', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.person', verbose_name='Person Name :')),
            ],
        ),
    ]
