# Generated by Django 3.1.5 on 2021-01-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(choices=[('Baroda', 'Baroda'), ('Surat', 'Surat'), ('Ahmedabad', 'Ahmedabad')], default='Baroda', max_length=100),
        ),
    ]
