# Generated by Django 3.1.5 on 2021-01-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_personsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(choices=[('', 'Select'), ('Baroda', 'Baroda'), ('Surat', 'Surat'), ('Ahmedabad', 'Ahmedabad')], default='Baroda', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='person',
            name='contactno',
            field=models.IntegerField(null=True, verbose_name='Contact No. :'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10, verbose_name='Gender :'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Full Name :'),
        ),
        migrations.AlterField(
            model_name='person',
            name='zipcode',
            field=models.IntegerField(null=True, verbose_name='Zip Code :'),
        ),
        migrations.AlterField(
            model_name='personsalary',
            name='userperson',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.person', verbose_name='Person Name :'),
        ),
    ]
